# Generated by Django 3.2 on 2021-04-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkyris_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='public',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
