# Generated by Django 3.2 on 2021-04-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkyris_api', '0002_auto_20210414_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='deleted',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='public',
            field=models.IntegerField(),
        ),
    ]
